select * from
(
select ITSDATE, SOURCEID, SOURCETYPE, ACCDEBIT as ACC, SUBACCDEBIT as SUBACC, DEBIT as ITSTOTAL, 1 as ISDEBIT,
ACCCREDIT as CORACC, ACCOUNT2.ITSNAME as CORACCNAME, ACCOUNT.ITSNUMBER as CORACCNUMBER, SUBACCCREDIT as CORSUBACC, ACCOUNTINGENTRY.DESCRIPTION 
from ACCOUNTINGENTRY 
join ACCOUNT on ACCOUNTINGENTRY.ACCDEBIT=ACCOUNT.ITSID
join ACCOUNT as ACCOUNT2 on ACCOUNTINGENTRY.ACCCREDIT=ACCOUNT2.ITSID
where ACCDEBIT=:ACCID :SUBACCDEBIT and ITSDATE >=:DATE1 and ITSDATE<=:DATE2

union all

select ITSDATE, SOURCEID, SOURCETYPE, ACCCREDIT as ACC, SUBACCCREDIT as SUBACC, CREDIT as ITSTOTAL, 0 as ISDEBIT,
ACCDEBIT as CORACC, ACCOUNT2.ITSNAME as CORACCNAME, ACCOUNT.ITSNUMBER as CORACCNUMBER, SUBACCDEBIT as CORSUBACC, ACCOUNTINGENTRY.DESCRIPTION 
from ACCOUNTINGENTRY 
join ACCOUNT on ACCOUNTINGENTRY.ACCCREDIT = ACCOUNT.ITSID
join ACCOUNT as ACCOUNT2 on ACCOUNTINGENTRY.ACCDEBIT=ACCOUNT2.ITSID
where ACCCREDIT=:ACCID :SUBACCCREDIT and ITSDATE >=:DATE1 and ITSDATE<=:DATE2
) as UNION_DETAIL
order by ITSDATE;
