select ITSDATE, SOURCEID, SOURCETYPE, ACC, UNION_DETAIL.DESCRIPTION, ITSTOTAL, ISDEBIT, CORACC, CORACCNAME, CORACCNUMBER,
case when DEBTORCREDITOR.ITSNAME is not null then DEBTORCREDITOR.ITSNAME 
when DEBTORCREDITORCATEGORY.ITSNAME is not null then DEBTORCREDITORCATEGORY.ITSNAME
when INVITEMCATEGORY.ITSNAME is not null then INVITEMCATEGORY.ITSNAME
when EMPLOYEECATEGORY.ITSNAME is not null then EMPLOYEECATEGORY.ITSNAME
when EMPLOYEE.ITSNAME is not null then EMPLOYEE.ITSNAME
when TAX.ITSNAME is not null then TAX.ITSNAME
when EXPENSE.ITSNAME is not null then EXPENSE.ITSNAME
when PROPERTY.ITSNAME is not null then PROPERTY.ITSNAME
when WAGETYPE.ITSNAME is not null then WAGETYPE.ITSNAME
when SERVICETOSALECATEGORY.ITSNAME is not null then SERVICETOSALECATEGORY.ITSNAME
when BANKACCOUNT.ITSNAME is not null then BANKACCOUNT.ITSNAME end as SUBACC,
case when DEBTORCREDITOR2.ITSNAME is not null then DEBTORCREDITOR2.ITSNAME 
when DEBTORCREDITORCATEGORY2.ITSNAME is not null then DEBTORCREDITORCATEGORY2.ITSNAME
when INVITEMCATEGORY2.ITSNAME is not null then INVITEMCATEGORY2.ITSNAME
when EMPLOYEECATEGORY2.ITSNAME is not null then EMPLOYEECATEGORY2.ITSNAME
when EMPLOYEE2.ITSNAME is not null then EMPLOYEE2.ITSNAME
when TAX2.ITSNAME is not null then TAX2.ITSNAME
when EXPENSE2.ITSNAME is not null then EXPENSE2.ITSNAME
when PROPERTY2.ITSNAME is not null then PROPERTY2.ITSNAME
when WAGETYPE2.ITSNAME is not null then WAGETYPE2.ITSNAME
when SERVICETOSALECATEGORY2.ITSNAME is not null then SERVICETOSALECATEGORY2.ITSNAME
when BANKACCOUNT2.ITSNAME is not null then BANKACCOUNT2.ITSNAME end as CORSUBACC
from
(
select ITSDATE, SOURCEID, SOURCETYPE, ACCDEBIT as ACC, SUBACCDEBITID as SUBACCID, SUBACCDEBITTYPE as SUBACCT, DEBIT as ITSTOTAL, 1 as ISDEBIT,
ACCCREDIT as CORACC, ACCOUNT.ITSNAME as CORACCNAME, ACCOUNT.ITSNUMBER as CORACCNUMBER, SUBACCCREDITID as CORSUBACCID, SUBACCCREDITTYPE as CORSUBACCT, ACCOUNTINGENTRY.DESCRIPTION 
from ACCOUNTINGENTRY 
join ACCOUNT on ACCOUNTINGENTRY.ACCDEBIT = ACCOUNT.ITSID
where ACCDEBIT=:ACCID :SUBACCDEBIT and ITSDATE >=:DATE1 and ITSDATE<=:DATE2

union all

select ITSDATE, SOURCEID, SOURCETYPE, ACCCREDIT as ACC, SUBACCCREDITID as SUBACCID, SUBACCCREDITTYPE as SUBACCT, CREDIT as ITSTOTAL, 0 as ISDEBIT,
ACCDEBIT as CORACC, ACCOUNT.ITSNAME as CORACCNAME, ACCOUNT.ITSNUMBER as CORACCNUMBER, SUBACCDEBITID as CORSUBACCID, SUBACCDEBITTYPE as CORSUBACCT, ACCOUNTINGENTRY.DESCRIPTION 
from ACCOUNTINGENTRY 
join ACCOUNT on ACCOUNTINGENTRY.ACCCREDIT = ACCOUNT.ITSID
where ACCCREDIT=:ACCID :SUBACCCREDIT and ITSDATE >=:DATE1 and ITSDATE<=:DATE2
) as UNION_DETAIL
left join DEBTORCREDITOR on UNION_DETAIL.SUBACCID=DEBTORCREDITOR.ITSID and UNION_DETAIL.SUBACCT=2004
left join DEBTORCREDITORCATEGORY on UNION_DETAIL.SUBACCID=DEBTORCREDITORCATEGORY.ITSID and UNION_DETAIL.SUBACCT=2005
left join BANKACCOUNT on UNION_DETAIL.SUBACCID=BANKACCOUNT.ITSID and UNION_DETAIL.SUBACCT=2002
left join INVITEMCATEGORY on UNION_DETAIL.SUBACCID=INVITEMCATEGORY.ITSID and UNION_DETAIL.SUBACCT=2001
left join EMPLOYEECATEGORY on UNION_DETAIL.SUBACCID=EMPLOYEECATEGORY.ITSID and UNION_DETAIL.SUBACCT=2007
left join EMPLOYEE on UNION_DETAIL.SUBACCID=EMPLOYEE.ITSID and UNION_DETAIL.SUBACCT=2006
left join TAX on UNION_DETAIL.SUBACCID=TAX.ITSID and UNION_DETAIL.SUBACCT=2003
left join EXPENSE on UNION_DETAIL.SUBACCID=EXPENSE.ITSID and UNION_DETAIL.SUBACCT=2009
left join PROPERTY on UNION_DETAIL.SUBACCID=PROPERTY.ITSID and UNION_DETAIL.SUBACCT=2010
left join WAGETYPE on UNION_DETAIL.SUBACCID=WAGETYPE.ITSID and UNION_DETAIL.SUBACCT=2008
left join SERVICETOSALECATEGORY on UNION_DETAIL.SUBACCID=SERVICETOSALECATEGORY.ITSID and UNION_DETAIL.SUBACCT=2011
left join DEBTORCREDITOR as DEBTORCREDITOR2 on UNION_DETAIL.CORSUBACCID=DEBTORCREDITOR2.ITSID and UNION_DETAIL.CORSUBACCT=2004
left join DEBTORCREDITORCATEGORY as DEBTORCREDITORCATEGORY2 on UNION_DETAIL.CORSUBACCID=DEBTORCREDITORCATEGORY2.ITSID and UNION_DETAIL.CORSUBACCT=2005
left join BANKACCOUNT as BANKACCOUNT2 on UNION_DETAIL.CORSUBACCID=BANKACCOUNT2.ITSID and UNION_DETAIL.CORSUBACCT=2002
left join INVITEMCATEGORY as INVITEMCATEGORY2 on UNION_DETAIL.CORSUBACCID=INVITEMCATEGORY2.ITSID and UNION_DETAIL.CORSUBACCT=2001
left join EMPLOYEECATEGORY as EMPLOYEECATEGORY2 on UNION_DETAIL.CORSUBACCID=EMPLOYEECATEGORY2.ITSID and UNION_DETAIL.CORSUBACCT=2007
left join EMPLOYEE as EMPLOYEE2 on UNION_DETAIL.CORSUBACCID=EMPLOYEE2.ITSID and UNION_DETAIL.CORSUBACCT=2006
left join TAX as TAX2 on UNION_DETAIL.CORSUBACCID=TAX2.ITSID and UNION_DETAIL.CORSUBACCT=2003
left join EXPENSE as EXPENSE2 on UNION_DETAIL.CORSUBACCID=EXPENSE2.ITSID and UNION_DETAIL.CORSUBACCT=2009
left join PROPERTY as PROPERTY2 on UNION_DETAIL.CORSUBACCID=PROPERTY2.ITSID and UNION_DETAIL.CORSUBACCT=2010
left join WAGETYPE as WAGETYPE2 on UNION_DETAIL.CORSUBACCID=WAGETYPE2.ITSID and UNION_DETAIL.CORSUBACCT=2008
left join SERVICETOSALECATEGORY as SERVICETOSALECATEGORY2 on UNION_DETAIL.CORSUBACCID=SERVICETOSALECATEGORY2.ITSID and UNION_DETAIL.CORSUBACCT=2011
order by ITSDATE;
