select ITEM.ITSNAME, ITEM.ITSID as ITEMID, DTLID, DTRM, DTCAT.ITSID as DTCID, DTCAT.ITSNAME as DTCNAME, DTCAT.AGGRONLYPERCENT as DTCRATE, DTCAT.TAXESDESCRIPTION as DTCDESCR,
OTCAT.ITSID as OTCID, OTCAT.ITSNAME as OTCNAME, OTCAT.AGGRONLYPERCENT as OTCRATE, OTCAT.TAXESDESCRIPTION as OTCDESCR
from :ITEMNM as ITEM
left join INVITEMTAXCATEGORY as OTCAT on OTCAT.ITSID=ITEM.TAXCATEGORY
left join (select DESTTAXITEMLN.ITSID as DTLID, TAXDESTINATION.SALTAXROUNDMODE as DTRM, DTCAT.ITSID as ITSID, DTCAT.ITSNAME as ITSNAME, DTCAT.AGGRONLYPERCENT, DTCAT.TAXESDESCRIPTION, DESTTAXITEMLN.ITSOWNER as ITEMID
from :DESTTAXITEMLNNM as DESTTAXITEMLN
join TAXDESTINATION on TAXDESTINATION.ITSID=DESTTAXITEMLN.ITSOWNER
left join INVITEMTAXCATEGORY as DTCAT on DTCAT.ITSID=DESTTAXITEMLN.TAXCATEGORY
where DESTTAXITEMLN.TAXDESTINATION=:TAXDESTID) as DTCAT on ITEM.ITSID=DTCAT.ITEMID
where ITEM.ITSID=:ITEMID;
