select ITEM.ITSNAME as ITEMID, ITEM.ITSID as ITEMID, DTCAT.ITSID as DTCID, DTCAT.ITSNAME as DTCNAME, DTCAT.AGGRONLYPERCENT as DTCRATE, DTCAT.TAXESDESCRIPTION as DTCDESCR,
OTCAT.ITSID as OTCID, OTCAT.ITSNAME as OTCNAME, OTCAT.AGGRONLYPERCENT as OTCRATE, OTCAT.TAXESDESCRIPTION as OTCDESCR
from SERVICETOSALE as ITEM
left join INVITEMTAXCATEGORY as OTCAT on OTCAT.ITSID=ITEM.TAXCATEGORY
left join (select DTCAT.ITSID as ITSID, DTCAT.ITSNAME as ITSNAME, DTCAT.AGGRONLYPERCENT, DTCAT.TAXESDESCRIPTION, DESTTAXITEMLN.ITSOWNER as ITEMID
from DESTTAXSERVSELLN as DESTTAXITEMLN
left join INVITEMTAXCATEGORY as DTCAT on DTCAT.ITSID=DESTTAXITEMLN.TAXCATEGORY
where DESTTAXITEMLN.TAXDESTINATION=:TAXDESTID) as DTCAT on ITEM.ITSID=DTCAT.ITEMID
where ITEM.ITSID=:ITEMID;
