select ITEM.ITSNAME as ITEMID, ITEM.ITSID as ITEMID, DTCAT.ITSID as DTCID, DTCAT.ITSNAME as DTCNAME, DTCAT.AGGRONLYPERCENT as DTCRATE, DTCAT.TAXESDESCRIPTION as DTCDESCR,
OTCAT.ITSID as OTCID, OTCAT.ITSNAME as OTCNAME, OTCAT.AGGRONLYPERCENT as OTCRATE, OTCAT.TAXESDESCRIPTION as OTCDESCR
from :ITEMNM as ITEM
left join INVITEMTAXCATEGORY as OTCAT on OTCAT.ITSID=ITEM.TAXCATEGORY
left join :DESTTAXITEMLNNM as DESTTAXITEMLN on ITEM.ITSID=DESTTAXITEMLN.ITSOWNER
left join INVITEMTAXCATEGORY as DTCAT on DTCAT.ITSID=DESTTAXITEMLN.TAXCATEGORY
where ITEM.ITSID=:ITEMID and DESTTAXITEMLN.TAXDESTINATION=:TAXDESTID;
