select 5 as SOURCETYPE, MANUFACTURE.ITSID as SOURCEID, null as SOURCEOWNERTYPE, null as SOURCEOWNERID, MANUFACTURE.ITSDATE as ITSDATE, THEREST
from MANUFACTURE
where REVERSEDID is null and IDDATABASEBIRTH=:IDDATABASEBIRTH and THEREST>0 and INVITEM=:INVITEM and UNITOFMEASURE=:UNITOFMEASURE
