select TAX as TAXID, ITSPERCENTAGE, sum(SUBTOTAL) as TAXABLE, sum(FOREIGNSUBTOTAL) as FOREIGNTAXABLE
from
(
  select INVITEM.TAXCATEGORY as TAXCATEGORY, SUBTOTAL, FOREIGNSUBTOTAL
  from PURCHASEINVOICELINE 
  join INVITEM on INVITEM.ITSID = PURCHASEINVOICELINE.INVITEM
  where PURCHASEINVOICELINE.REVERSEDID is null and PURCHASEINVOICELINE.ITSOWNER=:INVOICEID

  union all

  select SERVICEPURCHASED.TAXCATEGORY as TAXCATEGORY, SUBTOTAL, FOREIGNSUBTOTAL
  from PURCHASEINVOICESERVICELINE 
  join SERVICEPURCHASED on SERVICEPURCHASED.ITSID = PURCHASEINVOICESERVICELINE.SERVICE
  where PURCHASEINVOICESERVICELINE.ITSOWNER=:INVOICEID
) as ALL_LINES
join INVITEMTAXCATEGORY on INVITEMTAXCATEGORY.ITSID=TAXCATEGORY
join INVITEMTAXCATEGORYLINE on INVITEMTAXCATEGORYLINE.ITSOWNER=INVITEMTAXCATEGORY.ITSID
group by TAX;
