select TAXCATEGORY, sum(TOTALTAXES) as TOTALTAXES, sum(FOREIGNTOTALTAXES) as FOREIGNTOTALTAXES
from
(
  select TAXCATEGORY, TOTALTAXES, FOREIGNTOTALTAXES
  from PURCHASEINVOICELINE 
  where PURCHASEINVOICELINE.REVERSEDID is null and TAXCATEGORY is not null and PURCHASEINVOICELINE.ITSOWNER=:INVOICEID

  union all

  select TAXCATEGORY, TOTALTAXES, FOREIGNTOTALTAXES
  from PURCHASEINVOICESERVICELINE 
  where TAXCATEGORY is not null and PURCHASEINVOICESERVICELINE.ITSOWNER=:INVOICEID
) as ALL_LINES
group by TAXCATEGORY;
