select ILID, TAXCATEGORY as TAXCATID, TAX as TAXID, ITSPERCENTAGE, sum(TOTALTAXES) as TOTALTAXES
from
(
  select PURCHASERETURNLINE.ITSID as ILID, PURCHASEINVOICELINE.TAXCATEGORY, PURCHASERETURNLINE.TOTALTAXES
  from PURCHASERETURNLINE 
  join PURCHASEINVOICELINE on PURCHASEINVOICELINE.ITSID=PURCHASERETURNLINE.PURCHASEINVOICELINE
  where PURCHASERETURNLINE.REVERSEDID is null and PURCHASEINVOICELINE.TAXCATEGORY is not null and PURCHASERETURNLINE.ITSOWNER=:INVOICEID
) as ALL_LINES
join INVITEMTAXCATEGORY on INVITEMTAXCATEGORY.ITSID=TAXCATEGORY
join INVITEMTAXCATEGORYLINE on INVITEMTAXCATEGORYLINE.ITSOWNER=INVITEMTAXCATEGORY.ITSID
group by ILID, TAXCATID, TAXID, ITSPERCENTAGE;
