select sum(SUBTOTAL) as SUBTOTAL, sum(TOTALTAXES) as TOTALTAXES, sum(FOREIGNSUBTOTAL) as FOREIGNSUBTOTAL, sum(FOREIGNTOTALTAXES) as FOREIGNTOTALTAXES
from
(
  select SUBTOTAL, 0 as TOTALTAXES, FOREIGNSUBTOTAL, 0 as FOREIGNTOTALTAXES
  from PURCHASEINVOICELINE 
  where PURCHASEINVOICELINE.REVERSEDID is null and PURCHASEINVOICELINE.ITSOWNER=:ITSOWNER

  union all

  select SUBTOTAL, 0 as TOTALTAXES, FOREIGNSUBTOTAL, 0 as FOREIGNTOTALTAXES
  from PURCHASEINVOICESERVICELINE 
  where PURCHASEINVOICESERVICELINE.ITSOWNER=:ITSOWNER

  union all

  select 0 as SUBTOTAL, ITSTOTAL as TOTALTAXES, 0 as FOREIGNSUBTOTAL, FOREIGNTOTALTAXES
  from PURCHASEINVOICETAXLINE 
  where PURCHASEINVOICETAXLINE.ITSOWNER=:ITSOWNER
) as ALL_LINES;

