select sum(SUBTOTAL) as SUBTOTAL, sum(TOTALTAXES) as TOTALTAXES
from
(
  select SUBTOTAL, TOTALTAXES
  from PURCHASEINVOICELINE 
  where PURCHASEINVOICELINE.REVERSEDID is null and PURCHASEINVOICELINE.ITSOWNER = :ITSOWNER

  union all

  select ITSCOST as SUBTOTAL, TOTALTAXES
  from PURCHASEINVOICESERVICELINE 
  where PURCHASEINVOICESERVICELINE.ITSOWNER = :ITSOWNER
) as ALL_LINES;
