select ILID, TAXCATEGORY as TAXCATID, TAX as TAXID, ITSPERCENTAGE, sum(TOTALTAXES) as TOTALTAXES, sum(FOREIGNTOTALTAXES) as FOREIGNTOTALTAXES
from
(
  select ITSID as ILID, TAXCATEGORY, TOTALTAXES, FOREIGNTOTALTAXES
  from PURCHASEINVOICELINE 
  where PURCHASEINVOICELINE.REVERSEDID is null and TAXCATEGORY is not null and PURCHASEINVOICELINE.ITSOWNER=:INVOICEID

  union all

  select -ITSID as ILID, TAXCATEGORY, TOTALTAXES, FOREIGNTOTALTAXES
  from PURCHASEINVOICESERVICELINE 
  where TAXCATEGORY is not null and PURCHASEINVOICESERVICELINE.ITSOWNER=:INVOICEID
) as ALL_LINES
join INVITEMTAXCATEGORY on INVITEMTAXCATEGORY.ITSID=TAXCATEGORY
join INVITEMTAXCATEGORYLINE on INVITEMTAXCATEGORYLINE.ITSOWNER=INVITEMTAXCATEGORY.ITSID
group by ILID, TAXCATID, TAXID, ITSPERCENTAGE;
