select TAXCATEGORY as TAXCATID, TAX as TAXID, ITSPERCENTAGE, sum(SUBTOTAL) as SUBTOTAL, sum(ITSTOTAL) as ITSTOTAL
from
(
  select PURCHASEINVOICELINE.TAXCATEGORY, PURCHASERETURNLINE.SUBTOTAL, PURCHASERETURNLINE.ITSTOTAL
  from PURCHASERETURNLINE
  join PURCHASEINVOICELINE on PURCHASEINVOICELINE.ITSID=PURCHASERETURNLINE.PURCHASEINVOICELINE
  where PURCHASEINVOICELINE.TAXCATEGORY is not null and PURCHASERETURNLINE.REVERSEDID is null and PURCHASERETURNLINE.ITSOWNER=:INVOICEID
) as ALL_LINES
join INVITEMTAXCATEGORY on INVITEMTAXCATEGORY.ITSID=TAXCATEGORY
join INVITEMTAXCATEGORYLINE on INVITEMTAXCATEGORYLINE.ITSOWNER=INVITEMTAXCATEGORY.ITSID
group by TAXCATID, TAX, ITSPERCENTAGE;
