select TAXCATEGORY, sum(TOTALTAXES) as TOTALTAXES, sum(FOREIGNTOTALTAXES) as FOREIGNTOTALTAXES
from
(
  select INVITEM.TAXCATEGORY as TAXCATEGORY, TOTALTAXES, FOREIGNTOTALTAXES
  from PURCHASEINVOICELINE 
  join INVITEM on INVITEM.ITSID=PURCHASEINVOICELINE.INVITEM
  where PURCHASEINVOICELINE.REVERSEDID is null and INVITEM.TAXCATEGORY is not null and PURCHASEINVOICELINE.ITSOWNER=:INVOICEID

  union all

  select SERVICEPURCHASED.TAXCATEGORY as TAXCATEGORY, TOTALTAXES, FOREIGNTOTALTAXES
  from PURCHASEINVOICESERVICELINE 
  join SERVICEPURCHASED on SERVICEPURCHASED.ITSID=PURCHASEINVOICESERVICELINE.SERVICE
  where SERVICEPURCHASED.TAXCATEGORY is not null and PURCHASEINVOICESERVICELINE.ITSOWNER=:INVOICEID
) as ALL_LINES
group by TAXCATEGORY;
