select SALESINVOICESERVICELINE.ITSID as ITSID, SALESINVOICESERVICELINE.TAXESDESCRIPTION as TAXESDESCRIPTION, SALESINVOICESERVICELINE.ITSPRICE as ITSPRICE,
  SALESINVOICESERVICELINE.ITSTOTAL as ITSTOTAL, SALESINVOICESERVICELINE.TOTALTAXES as TOTALTAXES, SERVICETOSALE.ITSID as SERVICEITSID,
  case when I18NSERVICETOSALE.ITSNAME is null then SERVICETOSALE.ITSNAME else I18NSERVICETOSALE.ITSNAME  end as SERVICEITSNAME
from SALESINVOICESERVICELINE
left join SERVICETOSALE on SALESINVOICESERVICELINE.SERVICE=SERVICETOSALE.ITSID
left join (select ITSNAME, HASNAME from I18NSERVICETOSALE where LANG=':LANG') as I18NSERVICETOSALE on SERVICETOSALE.ITSID=I18NSERVICETOSALE.HASNAME
where SALESINVOICESERVICELINE.REVERSEDID is null and SALESINVOICESERVICELINE.ITSOWNER=:ITSOWNER;
