select SALESINVOICESERVICELINE.ITSID as ITSID, SALESINVOICESERVICELINE.TAXESDESCRIPTION as TAXESDESCRIPTION, SALESINVOICESERVICELINE.SUBTOTAL as SUBTOTAL, SALESINVOICESERVICELINE.ITSPRICE as ITSPRICE,
  SALESINVOICESERVICELINE.ITSQUANTITY as ITSQUANTITY, SALESINVOICESERVICELINE.ITSTOTAL as ITSTOTAL, SALESINVOICESERVICELINE.TOTALTAXES as TOTALTAXES, SERVICETOSALE.ITSID as SERVICEITSID, UNITOFMEASURE.ITSID as UNITOFMEASUREITSID,
  case when I18NSERVICETOSALE.ITSNAME is null then SERVICETOSALE.ITSNAME else I18NSERVICETOSALE.ITSNAME  end as SERVICEITSNAME,
  case when I18NUNITOFMEASURE.ITSNAME is null then UNITOFMEASURE.ITSNAME else I18NUNITOFMEASURE.ITSNAME  end as UNITOFMEASUREITSNAME
from SALESINVOICESERVICELINE
left join SERVICETOSALE on SALESINVOICESERVICELINE.SERVICE=SERVICETOSALE.ITSID
left join UNITOFMEASURE as UNITOFMEASURE on SALESINVOICESERVICELINE.UNITOFMEASURE=UNITOFMEASURE.ITSID
left join (select ITSNAME, HASNAME from I18NSERVICETOSALE where LANG=':LANG') as I18NSERVICETOSALE on SERVICETOSALE.ITSID=I18NSERVICETOSALE.HASNAME
left join (select ITSNAME, HASNAME from I18NUNITOFMEASURE where LANG=':LANG') as I18NUNITOFMEASURE on UNITOFMEASURE.ITSID=I18NUNITOFMEASURE.HASNAME
where SALESINVOICESERVICELINE.REVERSEDID is null and SALESINVOICESERVICELINE.ITSOWNER=:ITSOWNER;
