select TAX as TAXID,  sum(ITSTOTAL) as TOTALTAX
from
(
  select TAX, ITSTOTAL
  from SALESINVOICEGOODSTAXLINE 
  where REVERSEDID is null and INVOICEID=:INVOICEID

  union all

  select TAX, ITSTOTAL
  from SALESINVOICESERVICETAXLINE 
  where INVOICEID=:INVOICEID
) as ALL_LINES
group by TAX;
