select TAX as TAXID, ITSPERCENTAGE, sum(SUBTOTAL) as TAXABLE, sum(FOREIGNSUBTOTAL) as FOREIGNTAXABLE
from
(
  select INVITEM.TAXCATEGORY as TAXCATEGORY, SUBTOTAL, FOREIGNSUBTOTAL
  from SALESINVOICELINE 
  join INVITEM on INVITEM.ITSID = SALESINVOICELINE.INVITEM
  where SALESINVOICELINE.REVERSEDID is null and SALESINVOICELINE.ITSOWNER=:INVOICEID

  union all

  select SERVICETOSALE.TAXCATEGORY as TAXCATEGORY, SUBTOTAL, FOREIGNSUBTOTAL
  from SALESINVOICESERVICELINE 
  join SERVICETOSALE on SERVICETOSALE.ITSID = SALESINVOICESERVICELINE.SERVICE
  where SALESINVOICESERVICELINE.ITSOWNER=:INVOICEID
) as ALL_LINES
join INVITEMTAXCATEGORY on INVITEMTAXCATEGORY.ITSID=TAXCATEGORY
join INVITEMTAXCATEGORYLINE on INVITEMTAXCATEGORYLINE.ITSOWNER=INVITEMTAXCATEGORY.ITSID
group by TAX;
