select sum(SUBTOTAL) as SUBTOTAL, sum(TOTALTAXES) as TOTALTAXES
from
(
  select SUBTOTAL, TOTALTAXES
  from SALESINVOICELINE 
  where SALESINVOICELINE.REVERSEDID is null and SALESINVOICELINE.ITSOWNER = :ITSOWNER

  union all

  select SUBTOTAL, TOTALTAXES
  from SALESINVOICESERVICELINE 
  where SALESINVOICESERVICELINE.ITSOWNER = :ITSOWNER
) as ALL_LINES;
