select SALESINVOICELINE.ITSID as ITSID, SALESINVOICELINE.ITSPRICE as ITSPRICE, SALESINVOICELINE.SUBTOTAL as SUBTOTAL, SALESINVOICELINE.ITSTOTAL as ITSTOTAL,
  SALESINVOICELINE.TAXESDESCRIPTION as TAXESDESCRIPTION, SALESINVOICELINE.TOTALTAXES as TOTALTAXES, SALESINVOICELINE.ITSQUANTITY as ITSQUANTITY,
  INVITEM.ITSID as INVITEMITSID, UNITOFMEASURE.ITSID as UNITOFMEASUREITSID,
  SALESINVOICELINE.FOREIGNPRICE as FOREIGNPRICE, SALESINVOICELINE.FOREIGNSUBTOTAL as FOREIGNSUBTOTAL, SALESINVOICELINE.FOREIGNTOTALTAXES as FOREIGNTOTALTAXES, SALESINVOICELINE.FOREIGNTOTAL as FOREIGNTOTAL,
  case when I18NINVITEM.ITSNAME is null then INVITEM.ITSNAME else I18NINVITEM.ITSNAME  end as INVITEMITSNAME,
  case when I18NUNITOFMEASURE.ITSNAME is null then UNITOFMEASURE.ITSNAME else I18NUNITOFMEASURE.ITSNAME  end as UNITOFMEASUREITSNAME
from SALESINVOICELINE
left join INVITEM as INVITEM on SALESINVOICELINE.INVITEM=INVITEM.ITSID
left join UNITOFMEASURE as UNITOFMEASURE on SALESINVOICELINE.UNITOFMEASURE=UNITOFMEASURE.ITSID
left join (select ITSNAME, HASNAME from I18NINVITEM where LANG=':LANG') as I18NINVITEM on INVITEM.ITSID=I18NINVITEM.HASNAME
left join (select ITSNAME, HASNAME from I18NUNITOFMEASURE where LANG=':LANG') as I18NUNITOFMEASURE on UNITOFMEASURE.ITSID=I18NUNITOFMEASURE.HASNAME
where SALESINVOICELINE.REVERSEDID is null and SALESINVOICELINE.ITSOWNER=:ITSOWNER;
