select TAXCATEGORY, sum(TOTALTAXES) as TOTALTAXES, sum(FOREIGNTOTALTAXES) as FOREIGNTOTALTAXES
from
(
  select TAXCATEGORY, TOTALTAXES, FOREIGNTOTALTAXES
  from SALESINVOICELINE 
  where SALESINVOICELINE.REVERSEDID is null and TAXCATEGORY is not null and SALESINVOICELINE.ITSOWNER=:INVOICEID

  union all

  select TAXCATEGORY, TOTALTAXES, FOREIGNTOTALTAXES
  from SALESINVOICESERVICELINE 
  where TAXCATEGORY is not null and SALESINVOICESERVICELINE.ITSOWNER=:INVOICEID
) as ALL_LINES
group by TAXCATEGORY;
