select TAXCATEGORY, sum(TOTALTAXES) as TOTALTAXES, sum(FOREIGNTOTALTAXES) as FOREIGNTOTALTAXES
from
(
  select INVITEM.TAXCATEGORY as TAXCATEGORY, TOTALTAXES, FOREIGNTOTALTAXES
  from SALESINVOICELINE 
  join INVITEM on INVITEM.ITSID=SALESINVOICELINE.INVITEM
  where SALESINVOICELINE.REVERSEDID is null and INVITEM.TAXCATEGORY is not null and SALESINVOICELINE.ITSOWNER=:INVOICEID

  union all

  select SERVICETOSALE.TAXCATEGORY as TAXCATEGORY, TOTALTAXES, FOREIGNTOTALTAXES
  from SALESINVOICESERVICELINE 
  join SERVICETOSALE on SERVICETOSALE.ITSID=SALESINVOICESERVICELINE.SERVICE
  where SERVICETOSALE.TAXCATEGORY is not null and SALESINVOICESERVICELINE.ITSOWNER=:INVOICEID
) as ALL_LINES
group by TAXCATEGORY;
