select 10 as SOURCETYPE, PAYMENTFROM.:IDNAME as SOURCEID, PAYMENTFROM.ITSDATE as ITSDATE,
'AccReceivable' as ACCDEBIT, 2004 as SUBACCDEBITTYPE, DEBTORCREDITOR.ITSID as SUBACCDEBITID, DEBTORCREDITOR.ITSNAME as SUBACCDEBIT, sum(SALESINVOICETAXLINE.ITSTOTAL) as DEBIT,
'SalesTaxPay' as ACCCREDIT, 2003 as SUBACCCREDITTYPE, TAX.ITSID as SUBACCCREDITID, TAX.ITSNAME as SUBACCCREDIT, sum(SALESINVOICETAXLINE.ITSTOTAL) as CREDIT
from PAYMENTFROM
join SALESINVOICE on PAYMENTFROM.SALESINVOICE=SALESINVOICE.ITSID
join SALESINVOICETAXLINE on SALESINVOICE.ITSID=SALESINVOICETAXLINE.ITSOWNER
join TAX on TAX.ITSID=SALESINVOICETAXLINE.TAX
join DEBTORCREDITOR on DEBTORCREDITOR.ITSID=SALESINVOICE.CUSTOMER
where SALESINVOICETAXLINE.REVERSEDID is null and SALESINVOICE.REVERSEDID is null and SALESINVOICE.HASMADEACCENTRIES=1 and PAYMENTFROM.HASMADEACCENTRIES=0 and TAX.ITSTYPE in (1,2) and TAX.DUEMETHOD=1 and (SALESINVOICE.PAYMENTTOTAL+PAYMENTFROM.ITSTOTAL)>=SALESINVOICE.ITSTOTAL :WHEREADD
group by SOURCETYPE, SOURCEID, PAYMENTFROM.ITSDATE, ACCDEBIT, SUBACCDEBITTYPE, SUBACCDEBITID, SUBACCDEBIT, ACCCREDIT, SUBACCCREDITTYPE, SUBACCCREDITID, SUBACCCREDIT
