select 1 as SOURCETYPE, PURCHASEINVOICE.:IDNAME as SOURCEID, PURCHASEINVOICE.ITSDATE,
PURCHASEINVOICESERVICELINE.ACCEXPENSE as ACCDEBIT, 2009 as SUBACCDEBITTYPE, EXPENSE.ITSID as SUBACCDEBITID, EXPENSE.ITSNAME as SUBACCDEBIT, sum(PURCHASEINVOICESERVICELINE.SUBTOTAL) as DEBIT,
'AccPayable' as ACCCREDIT, 2004 as SUBACCCREDITTYPE, DEBTORCREDITOR.ITSID as SUBACCCREDITID, DEBTORCREDITOR.ITSNAME as SUBACCCREDIT, sum(PURCHASEINVOICESERVICELINE.SUBTOTAL) as CREDIT
from PURCHASEINVOICESERVICELINE
join PURCHASEINVOICE on PURCHASEINVOICE.ITSID=PURCHASEINVOICESERVICELINE.ITSOWNER
join SERVICEPURCHASED on SERVICEPURCHASED.ITSID=PURCHASEINVOICESERVICELINE.SERVICE
join SERVICEPURCHASEDCATEGORY on SERVICEPURCHASEDCATEGORY.ITSID=SERVICEPURCHASED.ITSCATEGORY
join EXPENSE on EXPENSE.ITSID=SERVICEPURCHASEDCATEGORY.EXPENSE 
join DEBTORCREDITOR on DEBTORCREDITOR.ITSID=PURCHASEINVOICE.VENDOR
where PURCHASEINVOICE.REVERSEDID is null and HASMADEACCENTRIES=0 :WHEREADD
group by SOURCETYPE, SOURCEID, ITSDATE, ACCDEBIT, SUBACCDEBITTYPE, SUBACCDEBITID, SUBACCDEBIT, ACCCREDIT, SUBACCCREDITTYPE, SUBACCCREDITID, SUBACCCREDIT
