select 2 as SOURCETYPE, SALESINVOICE.:IDNAME as SOURCEID, SALESINVOICE.ITSDATE as ITSDATE,
'AccReceivable' as ACCDEBIT, 2004 as SUBACCDEBITTYPE, DEBTORCREDITOR.ITSID as SUBACCDEBITID, DEBTORCREDITOR.ITSNAME as SUBACCDEBIT, sum(SALESINVOICESERVICELINE.SUBTOTAL) as DEBIT,
'SalesServices' as ACCCREDIT, 2011 as SUBACCCREDITTYPE, SERVICETOSALECATEGORY.ITSID as SUBACCCREDITID, SERVICETOSALECATEGORY.ITSNAME as SUBACCCREDIT, sum(SALESINVOICESERVICELINE.SUBTOTAL) as CREDIT
from SALESINVOICESERVICELINE
join SALESINVOICE on SALESINVOICE.ITSID=SALESINVOICESERVICELINE.ITSOWNER
join SERVICETOSALE on SERVICETOSALE.ITSID=SALESINVOICESERVICELINE.SERVICE
join SERVICETOSALECATEGORY on SERVICETOSALECATEGORY.ITSID=SERVICETOSALE.ITSCATEGORY
join DEBTORCREDITOR on DEBTORCREDITOR.ITSID=SALESINVOICE.CUSTOMER
where SALESINVOICE.REVERSEDID is null and HASMADEACCENTRIES=0 :WHEREADD
group by SOURCETYPE, SOURCEID, ITSDATE, ACCDEBIT, SUBACCDEBITTYPE, SUBACCDEBITID, SUBACCDEBIT, ACCCREDIT, SUBACCCREDITTYPE, SUBACCCREDITID, SUBACCCREDIT
